export const data=[
    {
        question: "What is the Capital of India?",
        option1: "Washington D.C",
        option2: "New Delhi",
        option3: "Melbourne",
        option4: "London",
        ans:2,
    },
    {
        question: "What is the Capital of Brazil?",
        option1: "Johnesburg",
        option2: "St.Petersburg",
        option3: "Capetown",
        option4: "Rio-De-Janiro",
        ans:4,
    },
    {
        question: "What is the Capital of Pelestine?",
        option1: "Jeruslam",
        option2: "New Delhi",
        option3: "Banglore",
        option4: "Malta",
        ans:1,
    },
    {
        question: "What is the Capital of Turkey?",
        option1: "New York City",
        option2: "Jeruslam",
        option3: "Istanbul",
        option4: "Amman",
        ans:3,
    },
    {
        question: "What is the Capital of England?",
        option1: "London",
        option2: "Paris",
        option3: "Singapore",
        option4: "Istanbul",
        ans:1,
    },
    {
        question: "What is the Capital of UAE?",
        option1: "Washington D.C",
        option2: "New Delhi",
        option3: "Melbourne",
        option4: "Dubai",
        ans:1,
    },
    {
        question: "What is the Capital of U.S?",
        option1: "Johnesburg",
        option2: "St.Petersburg",
        option3: "Washington D.C",
        option4: "Rio-De-Janiro",
        ans:3,
    },
    {
        question: "What is the Capital of Saudi Arabia?",
        option1: "Jeruslam",
        option2: "New Delhi",
        option3: "Banglore",
        option4: "Riyadh",
        ans:4,
    },
    {
        question: "What is the Capital of Lebanan?",
        option1: "Beirut",
        option2: "Jeruslam",
        option3: "Istanbul",
        option4: "Amman",
        ans:1,
    },
    {
        question: "What is the Capital of Germany?",
        option1: "London",
        option2: "Paris",
        option3: "Berlin",
        option4: "Istanbul",
        ans:3,
    },
];